nodeLinker: node-modules

npmScopes:
  cdek-it:
    npmRegistryServer: "https://npm.pkg.github.com"
  cdek-ui-kit:
    npmAlwaysAuth: true
    npmAuthToken: M__vw1BxxuyPg5htzoZw
    npmRegistryServer: "https://gitlab.cdek.ru/api/v4/projects/2094/packages/npm/"
