sonar.projectKey=cms_wordpress
sonar.qualitygate.wait=true

sonar.sources=.
sonar.exclusions=tests/**
sonar.tests=tests
sonar.php.tests.reportPath=junit-report.xml
sonar.php.coverage.reportPaths=coverage.xml
